### ISSUE TITLE
A way to run tests inside a custom monad

### ISSUE THREAD

**Issue by ocharles** [batterseapower/test-framework#30]
There is most likely a way to elegantly do this already, but I'm afraid I can't see it. All of my tests are integration tests that talk directly to a database, currently implemented by performing `runTest` for every `testCase`, which opens a database connection, runs the provided action in a `ReaderT DatabaseConnection` type monad, and finally yields `IO ()` for `testCase`. However, I'd really like to only open a database connection once per entire test run and re-use it for every test.

One option is to pass an environment to the test cases, and have them runReaderT against that environment - but that still makes declaring my test suite a bit of a pain. Is there a better way we could do this?

**Comment by batterseapower** [comment]
Could you use the buildTest combinator to do this? I.e. something like:

```
buildTestBracketed $ do { conn <- openDBConnection; return (tests conn, closeDBConnection conn) }

tests conn = testGroup "My DB tests" [.... conn ...]
```

**Comment by ocharles** [comment]
Well yes, but that means I still have to thread `conn` into every single test, along with consuming the `conn` in the actual test function itself.

**Comment by batterseapower** [comment]
It's not really clear to me how to actually implement the general case of running tests in a custom monad, because it involves deciding how to do this for each test provider for the framework, and extended the associated test libraries with the functionality.

Presumably I'd have to record the monad type in the type of Test, so every use of the type Test would become "Test m" instead.

Then I'd have to go and change HUnit to support running an assertion in a custom IO monad, and change my provider to use this functionality.

Then I'd have to go and change QuickCheck to support running a property in a custom IO monad... but I'm not quite sure what that would mean. Perhaps testProperty should have type (MonadIO m, Testable a) => String -> m a -> Test m? I guess I would need to provide two versions of testProperty so that people who don't want a monad can avoid the overhead of wrapping each property with "return".

It's possible but its not something I'm really inclined to do. If you really object to threading the conn, you can fix this without making any changes to test-framework by combining use my proposed approach with a Reader monad for the connection like so:

```
testGroupM :: String -> [Reader DBConn Test] -> Reader DBConn Test
testGroupM name tests = liftM (testGroup name) (sequence tests)

testCaseM :: String -> MyIOMonad () -> Reader DBConn Test
testCaseM name mx = do
  conn <- ask
  return $ testCase name (runMyIOMonad conn mx :: IO ())
```
